---
title: "Presence and Absences of effectors"
output: html_document
---

# Library
```{r}
#install.packages("ggplot2")
library(ggplot2)
```

# Function: Depth and breadth coverage
```{r}

DepthBreadth_function <- function(depth_data){
  
  #vectors results
  vdepth<- c()
  vbreath<- c()

  # walking in the list to calculate the depth and breath
  number_effector<- length(unique(depth_data$scaffold))
  # the lsit is to split depends the effectors
  listEffector<- split(depth_data, depth_data$scaffold)

  # for each effector calculate the depth and breath
  for(i in 1:number_effector){
   temporal_dataFrame<-listEffector[[i]]

    ## DEPTH
    depth<-round(mean(temporal_dataFrame[!(temporal_dataFrame$depth==0),3]),1)
    #depth<- round(mean(temporal_dataFrame[!(temporal_dataFrame$depth==0),3]),1)
    vdepth<-append(vdepth,depth)
    #df_DepthBreath[i, numCol_Depth]<- depth
  
    ## BREATH of coverage
    # length of all the effector
    effectorLength<-dim(temporal_dataFrame)[1]
    # lenght position differences to 0
    #my_effectorLength<-length(which(listEffector[[i]][3]>0, arr.ind = FALSE, useNames = TRUE))
    my_effectorLength<-dim(temporal_dataFrame[!(temporal_dataFrame$depth==0),])[1]

    breadth<- round((my_effectorLength/effectorLength)*100,1)
    #breadth<- round( ((my_effectorLength/effectorLength)*100),1) 
    #df_DepthBreath[i, numCol_Breath]<- breadth
    vbreath<- append(vbreath, breadth)
  } 
 return(list( vdepth, vbreath))
  }

```

# Load data 
```{r}
#getwd()
#setwd("/Volumes/tsl_hpc_home/TSL_2k/reyesac/rice_blast/cns_Herbarium_samples_Effectors/")
#setwd("~/Documents/Rice_blast/Data/")
myFiles <- list.files(pattern="*depth.txt")
```


# Extract depth and breath of coverage
```{r}
# creating empty data frame with names 
# read table 
depth_data <- read.table(myFiles[1],header=FALSE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE,stringsAsFactors=FALSE)
colnames(depth_data)<-c("scaffold", "position", "depth")
  
#changes for pretty names
depth_data$scaffold<- unlist(lapply(strsplit(depth_data$scaffold[], "_"), `[[`, 1))
  
#creating new empty data frame 
df_DepthBreath = data.frame(unique(sort(unlist(lapply(strsplit(depth_data$scaffold[], "_"), `[[`, 1)))))
colnames(df_DepthBreath)<- "Effectors"

for (i in 1:length(myFiles)){
  one_seqname<-strsplit(myFiles[i],"_")[[1]][1]
  
  # read table 
  depth_data <- read.table(myFiles[i],header=FALSE, sep="\t", na.strings="NA", dec=".", strip.white=TRUE,stringsAsFactors=FALSE)
  colnames(depth_data)<-c("scaffold", "position", "depth")
  
  depth_data$scaffold<- unlist(lapply(strsplit(depth_data$scaffold[], "_"), `[[`, 1))
  
  list.DepthBreadth<- DepthBreadth_function(depth_data)
  
  df_DepthBreath[paste0("Depth_",one_seqname)] <- list.DepthBreadth[[1]]
  df_DepthBreath[paste0("Breath_",one_seqname)] <- list.DepthBreadth[[2]]
  
}  

# Output of depth nd breath matrix
write.table(df_DepthBreath,"DepthBreath_knownThortenYohannExtrasEffectors_GladieuxZhong.txt",sep="\t",row.names=FALSE)
```

# Create binary breath matrix
```{r}
# select only the breath of coverage and reorganize in a matrix
Breath_prename<- df_DepthBreath[seq(1, length(1:ncol(df_DepthBreath)), 2)]
# reorganize effector names in df
effectors <- Breath_prename[,1]
df_Breath<- Breath_prename[,-1]
rownames(df_Breath) <- effectors
df2_Breath<-as.data.frame(t(df_Breath))

# Convert the porcenatge to binary
# If I have more than 80 per is 1
for (y in 2:ncol(df2_Breath)){
  for (x in 1:nrow(df2_Breath)){
    if (df2_Breath[x,y]>=80){
      df2_Breath[x,y]<-1
    }else{
      df2_Breath[x,y]<-0
    }
  }
}  

# Output of binary breath for all effectors
write.table(df2_Breath,"BinaryBreath_knownThortenYohannExtrasEffectors_GladieuxZhong_180effectors.txt",sep="\t",row.names=FALSE)

# Remove effectors that are present or absence in all the samples
shortListEffectors_Breath<-df2_Breath[colSums(df2_Breath[1,][col(df2_Breath)]!=df2_Breath)!=0]

# Output of binary breath for the short list of effectors
write.table(df_DepthBreath,"DepthBreath_knownThortenYohannExtrasEffectors_GladieuxZhong.txt",sep="\t",row.names=FALSE)
```

